# Generated by Django 3.2.14 on 2022-07-19 06:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0003_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='banner',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
