# Generated by Django 3.2.14 on 2022-07-19 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0005_rename_games_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='game',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='whiteboard.game'),
            preserve_default=False,
        ),
    ]
