# Generated by Django 3.2.14 on 2022-07-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0006_post_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='John', max_length=80),
            preserve_default=False,
        ),
    ]
