# Generated by Django 3.2.14 on 2022-07-24 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0008_remove_comment_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='boys_only',
        ),
        migrations.RemoveField(
            model_name='post',
            name='eighteen_plus',
        ),
        migrations.RemoveField(
            model_name='post',
            name='girls_only',
        ),
    ]
