# Generated by Django 3.2.14 on 2022-12-02 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0011_alter_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
